title: Joong의 블로그
author: Joong25
email: tbvjqlqlqlr@naver.com
description: >
  Hello, welcome. 

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- github.md

footer_icons:
- username: Joong25
  url: https://joong25.github.io
  icon: icon-github.svg

paginate: 2
paginate_path: "/posts/page:num/"

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
remote_theme: aterenin/minima-reboot
